# Generated by Django 5.0.10 on 2025-01-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rentals",
            "0003_rentalproperty_bathrooms_rentalproperty_is_available_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="apt_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("penwell", "Penwell"),
                    ("airbnb", "Airbnb"),
                ],
                default="residential",
                max_length=20,
            ),
        ),
    ]
