# Generated by Django 5.0.10 on 2025-02-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField()),
                ("phone", models.CharField(max_length=20)),
                ("account_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
