# Generated by Django 5.0.10 on 2025-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="account_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="bill",
            name="website",
            field=models.CharField(max_length=20),
        ),
    ]
