# Generated by Django 5.0.10 on 2025-01-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountInfo",
        ),
    ]
