# Generated by Django 5.0.10 on 2025-02-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='address',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='status',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
