# Generated by Django 5.0.10 on 2025-02-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_remove_maintenance_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintenance",
            old_name="title",
            new_name="street_address",
        ),
        migrations.AddField(
            model_name="maintenance",
            name="pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="urgency",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
